Open MPI: check for build dependencies
Check if libnuma and libibvers development libraries are installed
on the build machine. If not, show message and abort build.

In order to use CPU and memory affinity, Open MPI has to be compiled
with hwloc and libnuma support. The ./configure stage will disable
hwloc/libnuma if libnuma is not found.

ibverbs will be required for vRDMA usage.

Change-Id: I7af68e42d90a728f5f7a69b00bc7c1c444db0b64
Signed-off-by: Justin Cinkelj <justin.cinkelj@xlab.si>

diff --git a/open-mpi/GET b/open-mpi/GET
--- a/open-mpi/GET
+++ b/open-mpi/GET
@@ -7,6 +7,21 @@ VERSION='v1.10.2a2-osv-port'  # dcccfbb2
 BASEDIR="$PWD"
 SRCDIR="$BASEDIR/ompi-release"
 
+# Check for required build dependencies - libnuma-devel and libibverbs-devel.
+# Just search for .h file installed by specific lib.
+FF='numaif.h verbs.h'
+for ff in $FF; do
+    ffpath="`find /usr/include -iname $ff`"
+    if [ -z "$ffpath" ]; then
+        echo -e "Missing required devel libraries - libnuma-devel and libibverbs-devel.
+To install, run:
+sudo apt-get install libnuma-dev libibverbs-dev  # Ubuntu
+sudo yum install numactl-devel libibverbs-devel  # CentOS
+" 1>&2
+        exit 1
+    fi
+done
+
 CONFIGURE_FLAGS=""
 DISTRO_NAME=`python -c 'import platform; pp=platform.linux_distribution(); str="%s-%s" % (pp[0], pp[1]); str=str.replace(" ", "-").lower(); print(str); '`
 if [ "$mode" = "debug" ]; then
